version: '3.8'

services:

  db:
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: "12345678"
      POSTGRES_USER: "grimdan"
      POSTGRES_DB: "userservicedb"
    ports:
      - "127.0.0.1:5432:5432"
  web-app:
    restart: on-failure
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - local.env
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db
